services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: hibernate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  config-service:
    build: ./config-service
    ports:
      - "8888:8888"

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-service

  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - config-service

  user-service:
    build: ./spring
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - postgres
      - gateway-service
      - config-service

  notification-service:
    build: ./notification-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - gateway-service
      - config-service

  zookeeper:
    image: zookeeper:3.7
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper