server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notify/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka